[package]
name = "rust-dsmr"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.31"
dsmr5 = "0.3.0"
futures = "0.3.29"
influxdb = { version = "0.7.1", features = [
  "derive",
] }
influxdb2 = "0.4.4"
serialport = "4.2.2"
tokio = { version = "1.33.0", features = [
  "full",
] }
